### ISSUE TITLE
SSR: document is not defined

### ISSUE THREAD

**Issue by Linzdigr** [MetinSeylan/Vue-Socket.io#106]
When used to render on server side (following the official ssr vue.js guide) it produces 

```
ReferenceError: document is not defined
    at o.doPoll ([...]/foo/node_modules/vue-socket.io/dist/build.js:1:46051)
    at o.n.poll ([...]/foo/node_modules/vue-socket.io/dist/build.js:1:16090)
    at o.n.doOpen ([...]/foo/node_modules/vue-socket.io/dist/build.js:1:15561)
    at o.n.open ([...]/foo/node_modules/vue-socket.io/dist/build.js:1:9517)
    at n.open ([...]/foo/node_modules/vue-socket.io/dist/build.js:1:39567)
    at new n ([...]/foo/node_modules/vue-socket.io/dist/build.js:1:38099)
    at n ([...]/foo/node_modules/vue-socket.io/dist/build.js:1:36143)
    at n.open.n.connect ([...]/foo/node_modules/vue-socket.io/dist/build.js:1:21288)
    at new n ([...]/foo/node_modules/vue-socket.io/dist/build.js:1:19707)
    at n ([...]/foo/node_modules/vue-socket.io/dist/build.js:1:18948)
```

Is there a SSR support?

Vue-Socket.io is used in a vuex store in my project.

**Comment by Kronhyx** [comment]
i have the same problem...

**Comment by jmvillavicencio** [comment]
Me too

**Comment by probil** [comment]
SSR is not supported in `Vue-Socket.io` and it seems like it's not going to be supported in the near future. 

BTW: I've forked the library as [`vue-socket.io-extended`](https://github.com/probil/vue-socket.io-extended) and develop separately. Currently, it also doesn't support SSR fully but at least it does not crash. Check it out if you are interested.
