### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by MaksimSerg** [MetinSeylan/Vue-Socket.io#251]
ERROR in ./node_modules/vue-socket.io/dist/vue-socketio.js
Module parse failed: Unexpected token (10:14818)

**Desktop (please complete the following information):**
 - OS: ubuntu 18
 - node: 8.10.0
 - npm: 3.5.2

**Comment by nicodeur** [comment]
Hello, I have the same since 3.0.9

```
ERROR in ./~/vue-socket.io/dist/vue-socketio.js

Module parse failed: /home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/vue-socket.io/dist/vue-socketio.js Unexpected token (10:14929)

You may need an appropriate loader to handle this file type.

SyntaxError: Unexpected token (10:14929)

    at Parser.pp$4.raise (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)

    at Parser.pp.unexpected (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)

    at Parser.pp$3.parseIdent (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:2189:12)

    at Parser.pp$3.parsePropertyName (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:2052:101)

    at Parser.pp$3.parseObj (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:1988:14)

    at Parser.pp$3.parseExprAtom (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:1805:19)

    at Parser.pp$3.parseExprSubscripts (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)

    at Parser.pp$3.parseMaybeUnary (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)

    at Parser.pp$3.parseExprOps (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)

    at Parser.pp$3.parseMaybeConditional (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)

    at Parser.pp$3.parseMaybeAssign (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)

    at Parser.pp$3.parseMaybeAssign (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:1608:25)

    at Parser.pp$3.parseParenAndDistinguishExpression (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:1861:32)

    at Parser.pp$3.parseExprAtom (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:1796:19)

    at Parser.pp$3.parseExprSubscripts (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)

    at Parser.pp$3.parseMaybeUnary (/home/jenkins/agent/workspace/DM-MDM_KDM-MDM-mdm-front_develop/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
```

Any news about it ?

**Comment by X-H-siwan** [comment]
same error here

**Comment by nelsonkti** [comment]
@MetinSeylan
Help solve this problem

**Comment by MaksimSerg** [comment]
I just put in the old version - 3.0.7

**Comment by igwtech** [comment]
Same error on 3.0.9

**Comment by ray2031** [comment]
I installed 3.0.5 to solved this problem

**Comment by GuoChen-thlg** [comment]
I have the same problem
